package com.example.callingkotlinrepositories.utils

const val BASE_URL = "https://api.github.com/"
const val MY_PREFERENCE = "My preferences"
const val USER_NAME_OR_EMAIL = "user_key"
const val USER_PASSWORD = "user_password"
const val USER_AVATAR = "user_avatar"
const val USER_LOGIN_AS = "user_login_as"
const val REPOSITORY_ID = "repository_id"
const val REPOSITORY_FULL_NAME = "repository_full_name"
const val QUERY_ISSUE = "Issues"
const val QUERY_TYPE= ">2019-06-21"
const val DATE_FORMAT = "dd MMMM yyyy"
const val REPOSITORY_LIST_SAVED_STATE = "saved_state"
const val REPOSITORY_DETAILS_SAVED_STATE = "details_state"
const val REPOSITORY_LAST_YEAR_STATS_SAVED_STATE = "stats_state"
const val REPOSITORY_ISSUES_COUNTER_SAVED_STATE = "issues_state"